---
driver:
  name: docker

provisioner:
  name: ansible_playbook
  hosts: test-kitchen
  require_ansible_repo: false
  require_chef_for_busser: false
  require_ansible_omnibus: false
  ansible_version: 2.5.6.0
  ansible_verbose: true
  ansible_verbosity: 3
  ansible_extra_flags: <%= ENV['ANSIBLE_EXTRA_FLAGS'] %>
  ignore_paths_from_root:
    - .kitchen
  extra_vars:
    nodejs_npm_packages:
      - name: pad-left
        version: latest

platforms:
  - name: ubuntu-16.04
    driver_config:
      image: geerlingguy/docker-ubuntu1604-ansible
      platform: ubuntu
      provision_command:
        - apt-get install -y apt-transport-https

verifier:
  name: serverspec
  default_pattern: true

suites:
  - name: default
